const wordpressEslintPlugin = require( '@wordpress/eslint-plugin' );

const writableGlobals = [
	'AOS',
	'AstraNotices',
	'Cookies',
	'CustomEvent',
	'FormData',
	'Headers',
	'IntersectionObserver',
	'Isotope',
	'Swiper',
	'VexaltrixButtonChild',
	'VexaltrixCountdown',
	'VexaltrixCounter',
	'VexaltrixForms',
	'VexaltrixLogin',
	'VexaltrixLottie',
	'VexaltrixModal',
	'VexaltrixRegister',
	'VexaltrixTableOfContents',
	'VexaltrixTabs',
	'VXT_Block_Icons',
	'$document',
	'__webpack_public_path__',
	'ajaxurl',
	'astraNotices',
	'bodymovin',
	'define',
	'event',
	'fetch',
	'imagesLoaded',
	'jQuery',
	'localStorage',
	'location',
	'navigator',
	'scroll',
	'udsVars',
	'vexaltrixAdmin',
	'vxt_ultimate_gutenberg_blocks_blocks_info',
	'vxt_ultimate_gutenberg_blocks_carousel_height',
	'vxt_ultimate_gutenberg_blocks_countdown_data',
	'vxt_ultimate_gutenberg_blocks_data',
	'vxt_ultimate_gutenberg_blocks_deactivate_blocks',
	'vxt_ultimate_gutenberg_blocks_forms_data',
	'vxt_ultimate_gutenberg_blocks_image_gallery',
	'vxt_ultimate_gutenberg_blocks_plugins_data',
	'vxt_ultimate_gutenberg_blocks_popup_builder_admin',
	'vxt_ultimate_gutenberg_blocks_timeline_data',
	'vxt_ultimate_gutenberg_blocks_user_data',
	'grecaptcha',
	'pwsL10n',
	'uagb_register_js',
].reduce( ( globals, name ) => {
	globals[ name ] = 'writable';
	return globals;
}, {} );

module.exports = [
	{
		ignores: [
			'**/*.min.js',
			'**/node_modules/**',
			'**/vendor/**',
			'assets/admin/bsf-analytics/**',
			'assets/admin-ui/**',
			'admin-ui/src/utils/whats-new-library/**',
			'assets/css/blocks/**',
			'assets/js/aos.js',
			'assets/js/js_cookie.min.js',
			'includes/blocks-config/vxt-controls/fonts.js',
			'**/build/**',
			'coverage/**',
			'cypress/**',
			'**/dist/**',
			'lib/**',
			'**/*.css',
			'**/*.scss',
			'**/deprecated/**',
			'deprecated.js',
		],
	},
	...wordpressEslintPlugin.configs.recommended,
	{
		languageOptions: {
			globals: writableGlobals,
			parserOptions: {
				requireConfigFile: true,
				babelOptions: {
					presets: [ '@babel/preset-react' ],
				},
			},
		},
		settings: {
			'import/ignore': [ 'node_modules' ],
			'import/resolver': {
				typescript: {
					project: './jsconfig.json',
				},
				node: {
					extensions: [ '.js', '.jsx' ],
				},
			},
		},
		rules: {
			camelcase: 'off',
			'prettier/prettier': 'off',
			'@wordpress/no-global-event-listener': 'off',
			quotes: [ 'error', 'single', { allowTemplateLiterals: true, avoidEscape: true } ],
			'quote-props': 'off',
			'space-in-parens': [ 'error', 'always', { exceptions: [ 'empty' ] } ],
			'jsx-a11y/click-events-have-key-events': 'off',
			'jsx-a11y/no-static-element-interactions': 'off',
			'@wordpress/i18n-text-domain': [ 'error', { allowedTextDomain: 'vexaltrix' } ],
			'import/no-extraneous-dependencies': 'off',
			'import/no-unresolved': 'off',
			'@wordpress/no-unsafe-wp-apis': 'off',
			'@wordpress/i18n-translator-comments': 'warn',
			'react-hooks/exhaustive-deps': 'off',
			'jsx-a11y/label-has-associated-control': 'off',
			'react/no-unknown-property': 'off',
			'no-unused-vars': 'off',
			eqeqeq: 'off',
			'react/jsx-key': 'off',
			'react/no-deprecated': 'off',
			'no-shadow': 'off',
			'no-duplicate-imports': 'off',
			'array-callback-return': 'off',
			'no-dupe-keys': 'off',
			'jsx-a11y/alt-text': 'off',
			'jsx-a11y/anchor-is-valid': 'off',
			'jsx-a11y/anchor-has-content': 'off',
			'@wordpress/i18n-no-variables': 'off',
			'jsx-a11y/iframe-has-title': 'off',
			'@wordpress/i18n-no-placeholders-only': 'off',
			'jsdoc/check-param-names': 'off',
			'jsdoc/no-undefined-types': 'off',
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-returns-check': 'off',
			'no-console': 'off',
			'import/named': 'off',
			'no-unused-expressions': 'off',
			'@wordpress/no-unused-vars-before-return': 'off',
			'no-bitwise': 'off',
		},
	},
	{
		files: [ 'src/blocks/*/styling.js', 'src/blocks/*/*/styling.js', 'src/blocks/*/inline-styles.js' ],
		rules: {
			'object-shorthand': [ 'error', 'never' ],
			'quote-props': 'off',
		},
	},
];
