<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.2.0
 *
 * @package ugb
 */

$btnBorderAttributes = \Vexaltrix\Presentation\Blocks\BlockHelper::uagGenerateBorderAttribute(
	'btn'
);

$contentBorderAttributes = \Vexaltrix\Presentation\Blocks\BlockHelper::uagGenerateBorderAttribute(
	'content'
);
$additionalAttributes     = apply_filters( 'vexaltrix_modal_attributes', [] );
$additionalAttributes     = is_array( $additionalAttributes ) ? $additionalAttributes : [];
$inheritFromTheme        = 'enabled' === ( 'deleted' !== \Vexaltrix\Presentation\Admin\AdminSettings::get( 'vxt_btn_inherit_from_theme_fallback', 'deleted' ) ? 'disabled' : \Vexaltrix\Presentation\Admin\AdminSettings::get( 'vxt_btn_inherit_from_theme', 'disabled' ) );

return array_merge(
	[
		'modalTrigger'                => 'button',
		'inheritFromTheme'            => $inheritFromTheme,
		'buttonIconSpace'             => '5',
		'buttonIconSpaceTablet'       => '',
		'buttonIconSpaceMobile'       => '',
		'buttonIconSpaceType'         => 'px',
		'buttonIconPosition'          => 'after',
		'modalAlign'                  => 'left',
		'modalAlignTablet'            => '',
		'modalAlignMobile'            => '',
		'modalWidth'                  => 600,
		'modalWidthTablet'            => '',
		'modalWidthMobile'            => '',
		'modalWidthType'              => 'px',
		'modalWidthTypeTablet'        => '',
		'modalWidthTypeMobile'        => '',
		'modalHeight'                 => 350,
		'modalHeightTablet'           => '',
		'modalHeightMobile'           => '',
		'modalHeightType'             => 'px',
		'modalHeightTypeTablet'       => '',
		'modalHeightTypeMobile'       => '',
		'closeIconSize'               => 25,
		'closeIconPosition'           => 'popup-top-right',
		'overlayColor'                => 'rgba(0,0,0,0.75)',
		'closeIconColor'              => '',
		'paddingModalUnit'            => 'px',
		'mobilePaddingModalUnit'      => 'px',
		'tabletPaddingModalUnit'      => 'px',
		'paddingModalTop'             => '',
		'paddingModalBottom'          => '',
		'paddingModalLeft'            => '',
		'paddingModalRight'           => '',
		'paddingModalTopTablet'       => '',
		'paddingModalRightTablet'     => '',
		'paddingModalBottomTablet'    => '',
		'paddingModalLeftTablet'      => '',
		'paddingModalTopMobile'       => '',
		'paddingModalRightMobile'     => '',
		'paddingModalBottomMobile'    => '',
		'paddingModalLeftMobile'      => '',

		'iconSize'                    => 30,
		'iconColor'                   => '',
		'textColor'                   => '',

		'textFontFamily'              => '',
		'textLoadGoogleFonts'         => false,
		'textFontWeight'              => '',
		'textFontStyle'               => '',
		'textFontSize'                => '',
		'textFontSizeType'            => 'px',
		'textFontSizeTablet'          => '',
		'textFontSizeMobile'          => '',
		'textSpaceType'               => 'px',
		'textLineHeight'              => '',
		'textLineHeightType'          => 'em',
		'textLineHeightTablet'        => '',
		'textLineHeightMobile'        => '',
		'textLetterSpacing'           => '',
		'textLetterSpacingTablet'     => '',
		'textLetterSpacingMobile'     => '',
		'textLetterSpacingType'       => 'px',
		'textTransform'               => '',
		'textDecoration'              => '',

		'imageSize'                   => 'thumbnail',
		'imageWidthType'              => true,
		'imageWidth'                  => '',
		'imageWidthMobile'            => '',
		'imageWidthTablet'            => '',
		'imageWidthUnit'              => 'px',
		'imageWidthUnitTablet'        => 'px',
		'imageWidthUnitMobile'        => 'px',
		'iconimgBorderRadius'         => '0',
		'iconimgBorderRadiusUnit'     => 'px',

		'paddingBtnUnit'              => 'px',
		'mobilePaddingBtnUnit'        => 'px',
		'tabletPaddingBtnUnit'        => 'px',
		'paddingBtnTop'               => 14,
		'paddingBtnBottom'            => 14,
		'paddingBtnLeft'              => 32,
		'paddingBtnRight'             => 32,
		'paddingBtnTopTablet'         => '',
		'paddingBtnRightTablet'       => '',
		'paddingBtnBottomTablet'      => '',
		'paddingBtnLeftTablet'        => '',
		'paddingBtnTopMobile'         => '',
		'paddingBtnRightMobile'       => '',
		'paddingBtnBottomMobile'      => '',
		'paddingBtnLeftMobile'        => '',

		'btnFontFamily'               => '',
		'btnLoadGoogleFonts'          => false,
		'btnFontWeight'               => '',
		'btnFontStyle'                => '',
		'btnFontSize'                 => '',
		'btnFontSizeType'             => 'px',
		'btnFontSizeTablet'           => '',
		'btnFontSizeMobile'           => '',
		'btnSpaceType'                => 'px',
		'btnLineHeight'               => '',
		'btnLineHeightType'           => 'em',
		'btnLineHeightTablet'         => '',
		'btnLineHeightMobile'         => '',
		'btnLetterSpacing'            => '',
		'btnLetterSpacingTablet'      => '',
		'btnLetterSpacingMobile'      => '',
		'btnLetterSpacingType'        => 'px',
		'btnTransform'                => '',
		'btnDecoration'               => '',
		'btnLinkColor'                => '',
		'btnBgColor'                  => '',
		'btnLinkHoverColor'           => '',
		'btnBgHoverColor'             => '',
		'modalBoxHeight'              => 'auto',
		'maxHeight'                   => '90',
		'maxHeightTablet'             => '',
		'maxHeightMobile'             => '',
		'maxHeightType'               => 'vh',
		'backgroundType'              => 'none',
		'backgroundImageDesktop'      => '',
		'backgroundImageTablet'       => '',
		'backgroundImageMobile'       => '',
		'backgroundPositionDesktop'   => [
			'x' => 0.5,
			'y' => 0.5,
		],
		'backgroundPositionTablet'    => '',
		'backgroundPositionMobile'    => '',
		'backgroundSizeDesktop'       => 'cover',
		'backgroundSizeTablet'        => '',
		'backgroundSizeMobile'        => '',
		'backgroundRepeatDesktop'     => 'no-repeat',
		'backgroundRepeatTablet'      => '',
		'backgroundRepeatMobile'      => '',
		'backgroundAttachmentDesktop' => 'scroll',
		'backgroundAttachmentTablet'  => '',
		'backgroundAttachmentMobile'  => '',
		'backgroundColor'             => '',
		'backgroundOpacity'           => '',
		'backgroundImageColor'        => '#FFFFFF75',
		'gradientValue'               => 'linear-gradient(90deg, rgba(6, 147, 227, 0.5) 0%, rgba(155, 81, 224, 0.5) 100%)',
		'gradientColor1'              => '#06558a',
		'gradientColor2'              => '#0063A1',
		'gradientType'                => 'linear',
		'gradientLocation1'           => 0,
		'gradientLocationTablet1'     => '',
		'gradientLocationMobile1'     => '',
		'gradientLocation2'           => 100,
		'gradientLocationTablet2'     => '',
		'gradientLocationMobile2'     => '',
		'gradientAngle'               => 0,
		'gradientAngleTablet'         => '',
		'gradientAngleMobile'         => '',
		'selectGradient'              => 'basic',
		'backgroundCustomSizeDesktop' => 100,
		'backgroundCustomSizeTablet'  => '',
		'backgroundCustomSizeMobile'  => '',
		'backgroundCustomSizeType'    => '%',
		'overlayType'                 => 'none',
		'customPosition'              => 'default',
		'xPositionDesktop'            => '',
		'xPositionTablet'             => '',
		'xPositionMobile'             => '',
		'xPositionType'               => 'px',
		'xPositionTypeTablet'         => 'px',
		'xPositionTypeMobile'         => 'px',
		'yPositionDesktop'            => '',
		'yPositionTablet'             => '',
		'yPositionMobile'             => '',
		'yPositionType'               => 'px',
		'yPositionTypeTablet'         => 'px',
		'yPositionTypeMobile'         => 'px',
		'setCookiesOn'                => 'close-action',
		'modalTriggerBgType'          => 'color',
		'modalTriggerBgHoverType'     => 'color',
	],
	$btnBorderAttributes,
	[
		'btnBorderTopLeftRadius'     => 3,
		'btnBorderTopRightRadius'    => 3,
		'btnBorderBottomLeftRadius'  => 3,
		'btnBorderBottomRightRadius' => 3,
	],
	$contentBorderAttributes,
	[
		'contentBorderTopLeftRadius'     => 3,
		'contentBorderTopRightRadius'    => 3,
		'contentBorderBottomLeftRadius'  => 3,
		'contentBorderBottomRightRadius' => 3,
	],
	$additionalAttributes
);
