<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package ugb
 */

$defaultPadding = 20;

return [
	'block_id'                    => '',
	'backgroundType'              => 'none',
	'backgroundImageDesktop'      => '',
	'backgroundImageTablet'       => '',
	'backgroundImageMobile'       => '',
	'backgroundPositionDesktop'   => [
		'x' => 0.5,
		'y' => 0.5,
	],
	'backgroundPositionTablet'    => '',
	'backgroundPositionMobile'    => '',
	'backgroundSizeDesktop'       => 'cover',
	'backgroundSizeTablet'        => '',
	'backgroundSizeMobile'        => '',
	'backgroundRepeatDesktop'     => 'no-repeat',
	'backgroundRepeatTablet'      => '',
	'backgroundRepeatMobile'      => '',
	'backgroundAttachmentDesktop' => 'scroll',
	'backgroundAttachmentTablet'  => '',
	'backgroundAttachmentMobile'  => '',
	'backgroundColor'             => '',
	'backgroundOpacity'           => '',
	'gradientValue'               => 'linear-gradient(90deg, rgba(6, 147, 227, 0.5) 0%, rgba(155, 81, 224, 0.5) 100%)',
	'gradientColor1'              => '#06558a',
	'gradientColor2'              => '#0063A1',
	'gradientType'                => 'linear',
	'gradientLocation1'           => 0,
	'gradientLocationTablet1'     => '',
	'gradientLocationMobile1'     => '',
	'gradientLocation2'           => 100,
	'gradientLocationTablet2'     => '',
	'gradientLocationMobile2'     => '',
	'gradientAngle'               => 0,
	'gradientAngleTablet'         => '',
	'gradientAngleMobile'         => '',
	'selectGradient'              => 'basic',
	'backgroundImageColor'        => '#FFFFFF75',
	'backgroundCustomSizeDesktop' => 100,
	'backgroundCustomSizeTablet'  => '',
	'backgroundCustomSizeMobile'  => '',
	'backgroundCustomSizeType'    => '%',
	'overlayType'                 => 'none',
	'customPosition'              => 'default',
	'xPositionDesktop'            => '',
	'xPositionTablet'             => '',
	'xPositionMobile'             => '',
	'xPositionType'               => 'px',
	'xPositionTypeTablet'         => 'px',
	'xPositionTypeMobile'         => 'px',
	'yPositionDesktop'            => '',
	'yPositionTablet'             => '',
	'yPositionMobile'             => '',
	'yPositionType'               => 'px',
	'yPositionTypeTablet'         => 'px',
	'yPositionTypeMobile'         => 'px',
	'topPaddingDesktop'           => $defaultPadding,
	'bottomPaddingDesktop'        => $defaultPadding,
	'leftPaddingDesktop'          => $defaultPadding,
	'rightPaddingDesktop'         => $defaultPadding,
	'topPaddingTablet'            => $defaultPadding,
	'bottomPaddingTablet'         => $defaultPadding,
	'leftPaddingTablet'           => $defaultPadding,
	'rightPaddingTablet'          => $defaultPadding,
	'topPaddingMobile'            => $defaultPadding,
	'bottomPaddingMobile'         => $defaultPadding,
	'leftPaddingMobile'           => $defaultPadding,
	'rightPaddingMobile'          => $defaultPadding,
	'paddingType'                 => 'px',
	'paddingTypeTablet'           => 'px',
	'paddingTypeMobile'           => 'px',
	'paddingLink'                 => true,
	'topMarginDesktop'            => '',
	'bottomMarginDesktop'         => '',
	'leftMarginDesktop'           => '',
	'rightMarginDesktop'          => '',
	'topMarginTablet'             => '',
	'bottomMarginTablet'          => '',
	'leftMarginTablet'            => '',
	'rightMarginTablet'           => '',
	'topMarginMobile'             => '',
	'bottomMarginMobile'          => '',
	'leftMarginMobile'            => '',
	'rightMarginMobile'           => '',
	'marginType'                  => 'px',
	'marginTypeTablet'            => 'px',
	'marginTypeMobile'            => 'px',
];
